porfolio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('projects.urls')),

]

projects/urls.py

from . import views
from django.urls import path

app_name = 'projects'
urlpatterns = [
    path('',views.all_projects,name='home'),
    path('<int:pk>/', views.project_detail,name='detail')
]

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title= models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    technology = models.CharField(max_length=100)
    image = models.ImageField()

projects/views.py

from django.shortcuts import render
from projects.models import Project

# Create your views here.

def all_projects(request):
   projects= Project.objects.all()
   return render(request,'projects/index.html',{'projects':projects})


def project_detail(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request,'projects/detail.html',{'project':project})

projects/templates/projects/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Portfolio</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                   <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'projects:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    
                </ul>
                <span class="navbar-text">
                    Django Portfolio
                </span>
            </div>
        </div>
    </nav>
    {% block content %}


    {% endblock %}
</body>
</html>

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}
    <style>
        img {
            margin: 10px;
            max-width: 400px;
            height: 250px;
        }
    </style>
    <h1>{{project.title}}</h1>
<div class="row">

    <div class="col-md-6">
        <img src="{% static project.image %}" alt="{{project.description}}" />

    </div>
    <div>
        <p>Description: {{project.description}}</p>
        <h5>Built in:</h5>
        <p>{{project.technology}}</p>

    </div>
</div>
    
   
{% endblock %}


projects/templates/projects/index.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content%}
    <style>
        img {
            margin: 10px;
            max-width: 300px;
            height: 200px;
        }
    </style>

       
        <div class="row">
            {% for project in projects %}
            <div class="col-md-4">
                <div class="card mb-2">
                    <img class="card-img-top" src="{% static project.image %}">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.title }}</h5>
                        <p class="card-text">{{ project.description }}</p>
                        <a href="{% url 'projects:detail' project.pk %}"
                           class="btn btn-primary">
                            Read More
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
  
{% endblock %}